# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\x12\x08pingpong\"\x1e\n\x0bPingPongMsg\x12\x0f\n\x07payload\x18\x01 \x01(\t2@\n\x08PingPong\x12\x34\n\x04ping\x12\x15.pingpong.PingPongMsg\x1a\x15.pingpong.PingPongMsgB\x18\n\x16tech.sikorski.pingpongb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pingpong_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026tech.sikorski.pingpong'
  _PINGPONGMSG._serialized_start=28
  _PINGPONGMSG._serialized_end=58
  _PINGPONG._serialized_start=60
  _PINGPONG._serialized_end=124
# @@protoc_insertion_point(module_scope)
